version: "3.7"
services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/private-internet-access
    cap_add:
      - NET_ADMIN # required to modify network interfaces
    #restart: unless-stopped
    restart: always
    network_mode: bridge
    ports:
      #- 9091:9091 # Transmission web UI
      #- 51413:51413 # Transmission bittorrent daemon
      #- 51413:51413/udp # Transmission bittorrent daemon
      - 8112:8112 # port for deluge web UI to be reachable from local network
    volumes:
      - ${ROOT}/gluetun:/gluetun
    environment:
      # More variables are available, see the readme table
      - VPNSP=private internet access

      # Timezone for accurate logs times
      - TZ=${TZ}

      # All VPN providers
      - USER=${VPN_User}

      # All VPN providers but Mullvad
      - PASSWORD=${VPN_Pass}

      # All VPN providers but Mullvad
      - REGION=US Chicago

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: "service:gluetun" # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${ROOT}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${ROOT}/config/jackett:/config # config files

#  nzbget:
#    container_name: nzbget
#    image: linuxserver/nzbget:latest
#    restart: unless-stopped
#    network_mode: host
#    environment:
#      - PUID=${PUID} # default user id, defined in .env
#      - PGID=${PGID} # default group id, defined in .env
#      - TZ=${TZ} # timezone, defined in .env
#    volumes:
#      - ${ROOT}/downloads:/downloads # download folder
#      - ${ROOT}/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/sonarr:/config # config files
      - ${ROOT}/complete/tv:/tv # tv shows folder
      - ${ROOT}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/config/radarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/downloads:/downloads # download folder

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
      - UMASK_SET=022 #optional
    volumes:
      - ${ROOT}/config/bazarr:/config # config files
      - ${ROOT}/complete/movies:/movies # movies folder
      - ${ROOT}/complete/tv:/tv # tv shows folder
#    ports:
#      - 6767:6767
