services:
  gluetun:
    image: qmcgaw/private-internet-access
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # Tinyproxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 8112:8112 # deluge
      - 8989:8989 # sonarr
      - 9117:9117 # jackett
      - 7878:7878 # radarr
      - 6789:6789 # nzbget
      - 5076:5076 # hydra2
    # command:
    environment:
      - VPNSP=private internet access
      - TZ=${TZ}
      - USER=XXXXXXX # Your username
      - PASSWORD=YYYYYY # Your password
      - REGION=ZZZZZZ # Your region, e.g. US East. No quotes.
      - EXTRA_SUBNETS=10.0.0.0/8
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA}/unsorted:/downloads
      - ${ROOT}/config/deluge:/config
    network_mode: service:gluetun 
    depends_on:
      - jackett
      - gluetun

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/sonarr:/config 
      - ${MEDIA}/tv:/tv 
      - ${MEDIA}/unsorted:/downloads 
    network_mode: service:gluetun
    depends_on:
      - jackett
      - gluetun

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${MEDIA}/unsorted:/downloads
      - ${ROOT}/config/jackett:/config
    network_mode: service:gluetun
    depends_on:
      - gluetun

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/radarr:/config 
      - ${MEDIA}/movies:/movies 
      - ${MEDIA}/unsorted:/downloads
    network_mode: service:gluetun
    depends_on:
      - jackett
      - gluetun

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} 
    volumes:
      - ${MEDIA}/unsorted:/downloads 
      - ${ROOT}/config/nzbget:/config 
    network_mode: service:gluetun
    depends_on:
      - jackett
      - gluetun

  hydra2:
    image: linuxserver/nzbhydra2
    container_name: hydra2
    restart: unless-stopped
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ} 
    network_mode: service:gluetun
    volumes:
      - ${ROOT}/config/hydra2:/config
      - ${MEDIA}/unsorted:/downloads
    depends_on:
      - gluetun
      - jackett
